name: alphabet
description: "A new Flutter project."
publish_to: "none"

version: 2.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_image_slider: ^0.0.2
  dio: ^5.6.0
  auto_size_text: ^3.0.0
  jiffy: ^6.3.1
  webview_flutter:
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  google_mobile_ads: ^5.1.0
  firebase_core: ^3.4.1
  firebase_messaging: ^15.1.1
  flutter_local_notifications: ^17.2.2
  visibility_detector: ^0.4.0+2
  http: ^1.2.2
  restart_app: ^1.3.2
  app_set_id: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
